window.COOKIE_DB = {
  necessary: [
    { n: 'SOCS', d: 'google.com' },
    { n: 'AEC', d: 'google.com' },
    { n: 'CONSENT', d: 'google.com' },
    { n: 'PHPSESSID', d: 'www.google.com' },
    { n: 'JSESSIONID', d: 'www.google.com' },
    { n: 'csrftoken', d: 'www.google.com' },
    { n: 'XSRF-TOKEN', d: 'www.google.com' },
    { n: '__Host-session', d: 'www.google.com' },
    { n: '__cf_bm', d: 'cloudflare.com' },
    { n: 'cf_clearance', d: 'cloudflare.com' },
    { n: 'AWSALB', d: 'amazonaws.com' },
    { n: 'cookieconsent_status', d: 'www.google.com' }
  ],
  chaser: [
    { n: '__utma', d: 'google-analytics.com' },
    { n: '__utmz', d: 'google-analytics.com' },
    { n: '__utmb', d: 'google-analytics.com' },
    { n: '_ga', d: 'google-analytics.com' },
    { n: '_gid', d: 'google-analytics.com' },
    { n: '_gat', d: 'google-analytics.com' },
    { n: '_gcl_au', d: 'googleadservices.com' },
    { n: '_fbp', d: 'facebook.com' },
    { n: '_hjid', d: 'hotjar.com' },
    { n: '_clck', d: 'clarity.ms' },
    { n: '_uetsid', d: 'bing.com' },
    { n: 'ajs_anonymous_id', d: 'segment.io' },
    { n: 'mp_mixpanel', d: 'mixpanel.com' },
    { n: '_pin_unauth', d: 'pinterest.com' },
    { n: '__qca', d: 'quantserve.com' },
    { n: 'NID', d: 'google.com' }
  ],
  shooter: [
    { n: 'IDE', d: 'doubleclick.net' },
    { n: 'test_cookie', d: 'doubleclick.net' },
    { n: 'fr', d: 'facebook.com' },
    { n: 'MUID', d: 'bing.com' },
    { n: 'uuid2', d: 'adnxs.com' },
    { n: 'anj', d: 'adnxs.com' },
    { n: 'uid', d: 'criteo.com' },
    { n: 'cto_bundle', d: 'criteo.com' },
    { n: 't_gid', d: 'taboola.com' },
    { n: 'obuid', d: 'outbrain.com' },
    { n: 'UID', d: 'scorecardresearch.com' },
    { n: 'mc', d: 'quantserve.com' },
    { n: 'khaos', d: 'rubiconproject.com' },
    { n: 'KADUSERCOOKIE', d: 'pubmatic.com' },
    { n: 'TDID', d: 'adsrvr.org' },
    { n: 'ad-id', d: 'amazon-adsystem.com' },
    { n: 'demdex', d: 'demdex.net' },
    { n: 'bcookie', d: 'linkedin.com' },
    { n: 'personalization_id', d: 'twitter.com' },
    { n: '_ttp', d: 'tiktok.com' },
    { n: 'YSC', d: 'youtube.com' },
    { n: 'VISITOR_INFO1_LIVE', d: 'youtube.com' },
    { n: 'everest_g_v2', d: 'everesttech.net' },
    { n: 'A3', d: 'yahoo.com' },
    { n: 'tuuid', d: 'bidswitch.net' },
    { n: 'i', d: 'openx.net' }
  ],
  boss: [
    { n: 'evercookie', d: 'samy.pl' },
    { n: 'zombie cookie', d: 'kissmetrics.com' },
    { n: 'UIDH supercookie', d: 'verizon.net' },
    { n: 'Flash LSO', d: 'macromedia.com' }
  ]
};
